package com.freegrownextgen.freegrow.enums.auth;

public enum AuthEnums {
    SUCCESS,
    ERROR,
    UNAUTHORIZED,
    BAD_REQUEST,
    USER_EXISTS,
    INVLAID_EMAIL_ID,
    INVALID_MOBILE_NUMBER,
    INTERNAL_SERVER_ERROR,
    OTP_SENT,
    INVALID_OTP,
    USER_NOT_FOUND,
    INVLAID_NAME,
    INVALID_USER_LOGIN_TYPE_GOOGLE,
    INVALID_USER_LOGIN_TYPE,
    LINK_EXPIRED
}
